version: "3.9"
services:
  # Serviço Node.js
  node-app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres-container
      # - env_file: .env
    environment:
      - DB_HOST=postgres-container
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_BASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}

  # Serviço PostgreSQL
  postgres-container:
    image: postgres:13.2-alpine
    restart: always 
    container_name: postgres-container
    environment:
      # - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_BASE}
    ports:
      - "1981:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local